### ISSUE TITLE
Dashboard UX/UI Plan

### ISSUE THREAD

**Issue by gmemstr** [NodeMC/Dashboard#1]
Goal: Rewrite the existing dashboard using React for faster and smoother updating of UI information.
- [x] Implement log fetching
- [ ] User API key input & validation
- [ ] Implement command sending
- [ ] User-defined log fetch timing
- [ ] File browser
- [ ] Custom file editor (may stick with CodeMirror)
- [ ] Smooth transitions
- [ ] Night mode
## Basic UI guidelines

Following Material Design as closely as possible, and using NodeMC colours.
- Main accent: #2FB502
- Secondary accent: #CB0000 (Subject to change)

Dark colours will be based on colours, just with more darkness.
- Font: Roboto
- CSS Framework: Skeleton (for grid system)
## React components
- [ ] Header
  - [ ] Server stats
- [ ] Log / Console
  - [x] Log
  - [ ] Command input
- [ ] File browser
  - [ ] File listing
    - [ ] File name
    - [ ] File size (drop if NodeMC does not support)
    - [ ] File download link
    - [ ] File delete link
- [ ] File editor (CodeMirror [fork?])
- [ ] Settings
  - [ ] Log fetch timing
  - [ ] Night/day mode switch
  - [ ] Custom CSS (optional)
  - [ ] API key input / change

![screenshot - 16-05-13 - 05 29 16 pm](https://cloud.githubusercontent.com/assets/1878840/15270316/edb1222c-19cf-11e6-9da4-6e5f9ef90fce.png)

**Comment by mdcfe** [comment]
Might be worth using [CodeMirror as a React component](https://github.com/JedWatson/react-codemirror)

**Comment by mdcfe** [comment]
Closing in favour of NodeMC/NodeMC#1.
